package com.bawnorton.dcfixes.client.config;

import com.bawnorton.dcfixes.config.DCFixesConfig;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.BooleanControllerBuilder;
import dev.isxander.yacl3.api.controller.DoubleFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.FloatFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerFieldControllerBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

public class DCFixesConfigScreenHandler {

    public static Screen generateConfigScreen(Screen screen) {
        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("config.dcfixes.title"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.dcfixes.category.general"))
                        .tooltip(Component.translatable("config.dcfixes.category.general.tooltip"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.dcfixes.category.general.group.hordes"))
                                .description(OptionDescription.of(Component.translatable("config.dcfixes.category.general.group.hordes.description")))
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.horde_waves_loaded_distance_buffer"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.horde_waves_loaded_distance_buffer.description")))
                                        .binding(32, () -> DCFixesConfig.get().hordeWavesLoadedDistanceBuffer, value -> DCFixesConfig.get().hordeWavesLoadedDistanceBuffer = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, 512))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.dcfixes.category.general.group.debug"))
                                .description(OptionDescription.of(Component.translatable("config.dcfixes.category.general.group.debug.description")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.ragdoll_debug"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.ragdoll_debug.description")))
                                        .binding(false, () -> DCFixesConfig.get().ragdollDebug, value -> DCFixesConfig.get().ragdollDebug = value)
                                        .controller(option -> BooleanControllerBuilder.create(option).yesNoFormatter())
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.dcfixes.category.iv"))
                        .tooltip(Component.translatable("config.dcfixes.category.iv.tooltip"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.dcfixes.category.iv.group.rendering"))
                                .description(OptionDescription.of(Component.translatable("config.dcfixes.category.iv.group.rendering.description")))
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.frustum_cull_expansion"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.frustum_cull_expansion.description")))
                                        .binding(2D, () -> DCFixesConfig.get().frustumCullExpansion, value -> DCFixesConfig.get().frustumCullExpansion = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, 10D))
                                        .build()
                                )
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.dormant_dynamic_batch_distance"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.dormant_dynamic_batch_distance.description")))
                                        .binding(16D, () -> DCFixesConfig.get().dormantDynamicBatchDistance, value -> DCFixesConfig.get().dormantDynamicBatchDistance = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, 512D))
                                        .build()
                                )
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.particle_spawn_distance"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.particle_spawn_distance.description")))
                                        .binding(16D, () -> DCFixesConfig.get().particleSpawnDistance, value -> DCFixesConfig.get().particleSpawnDistance = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, 512D))
                                        .build()
                                )
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.instrument_render_distance"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.instrument_render_distance.description")))
                                        .binding(16D, () -> DCFixesConfig.get().instrumentRenderDistance, value -> DCFixesConfig.get().instrumentRenderDistance = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, 128D))
                                        .build()
                                )
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.text_render_distance"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.text_render_distance.description")))
                                        .binding(32D, () -> DCFixesConfig.get().textRenderDistance, value -> DCFixesConfig.get().textRenderDistance = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, 128D))
                                        .build()
                                )
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.dcfixes.category.iv.group.ticking"))
                                .description(OptionDescription.of(Component.translatable("config.dcfixes.category.iv.group.ticking.description")))
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.dormant_ticking_distance"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.dormant_ticking_distance.description")))
                                        .binding(16D, () -> DCFixesConfig.get().dormatTickingDistance, value -> DCFixesConfig.get().dormatTickingDistance = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, 512D))
                                        .build()
                                )
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.aircraft_always_tick"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.aircraft_always_tick.description")))
                                        .binding(true, () -> DCFixesConfig.get().aircraftAlwaysTick, value -> DCFixesConfig.get().aircraftAlwaysTick = value)
                                        .controller(option -> BooleanControllerBuilder.create(option).yesNoFormatter())
                                        .build()
                                )
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("config.dcfixes.category.extreme_reactors"))
                        .tooltip(Component.translatable("config.dcfixes.category.extreme_reactors.tooltip"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("config.dcfixes.category.extreme_reactors.group.turbine"))
                                .description(OptionDescription.of(Component.translatable("config.dcfixes.category.extreme_reactors.group.turbine.description")))
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.part_energy_capacity"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.part_energy_capacity.description")))
                                        .binding(20000, () -> DCFixesConfig.get().reinforcedPartEnergyCapacity, value -> DCFixesConfig.get().reinforcedPartEnergyCapacity = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, Integer.MAX_VALUE))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_energy_generation_efficiency"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_energy_generation_efficiency.description")))
                                        .binding(1F, () -> DCFixesConfig.get().reinforcedEnergyGenerationEfficiency, value -> DCFixesConfig.get().reinforcedEnergyGenerationEfficiency = value)
                                        .controller(option -> FloatFieldControllerBuilder.create(option).range(0F, 1F))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_max_energy_extraction_rate"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_max_energy_extraction_rate.description")))
                                        .binding(5.0E7, () -> DCFixesConfig.get().reinforcedMaxEnergyExtractionRate, value -> DCFixesConfig.get().reinforcedMaxEnergyExtractionRate = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, Double.MAX_VALUE))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_max_charger_rate"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_max_charger_rate.description")))
                                        .binding(25000D, () -> DCFixesConfig.get().reinforcedMaxChargerRate, value -> DCFixesConfig.get().reinforcedMaxChargerRate = value)
                                        .controller(option -> DoubleFieldControllerBuilder.create(option).range(0D, Double.MAX_VALUE))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_radiation_attenuation"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_radiation_attenuation.description")))
                                        .binding(0.75F, () -> DCFixesConfig.get().reinforcedRadiationAttenuation, value -> DCFixesConfig.get().reinforcedRadiationAttenuation = value)
                                        .controller(option -> FloatFieldControllerBuilder.create(option).range(0F, 1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_residual_radiation_attenuation"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_residual_radiation_attenuation.description")))
                                        .binding(0.15F, () -> DCFixesConfig.get().reinforcedResidualRadiationAttenuation, value -> DCFixesConfig.get().reinforcedResidualRadiationAttenuation = value)
                                        .controller(option -> FloatFieldControllerBuilder.create(option).range(0F, 1F))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_max_permitted_flow"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_max_permitted_flow.description")))
                                        .binding(2000, () -> DCFixesConfig.get().reinforcedMaxPermittedFlow, value -> DCFixesConfig.get().reinforcedMaxPermittedFlow = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, Integer.MAX_VALUE))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_base_fluid_per_blade"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_base_fluid_per_blade.description")))
                                        .binding(25, () -> DCFixesConfig.get().reinforcedBaseFluidPerBlade, value -> DCFixesConfig.get().reinforcedBaseFluidPerBlade = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, Integer.MAX_VALUE))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_rotor_drag_coefficient"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_rotor_drag_coefficient.description")))
                                        .binding(0.01F, () -> DCFixesConfig.get().reinforcedRotorDragCoefficient, value -> DCFixesConfig.get().reinforcedRotorDragCoefficient = value)
                                        .controller(option -> FloatFieldControllerBuilder.create(option).range(0F, 1F))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_max_rotor_speed"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_max_rotor_speed.description")))
                                        .binding(2000F, () -> DCFixesConfig.get().reinforcedMaxRotorSpeed, value -> DCFixesConfig.get().reinforcedMaxRotorSpeed = value)
                                        .controller(option -> FloatFieldControllerBuilder.create(option).range(0F, Float.MAX_VALUE))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_rotor_blade_mass"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_rotor_blade_mass.description")))
                                        .binding(10, () -> DCFixesConfig.get().reinforcedRotorBladeMass, value -> DCFixesConfig.get().reinforcedRotorBladeMass = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, Integer.MAX_VALUE))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_rotor_shaft_mass"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_rotor_shaft_mass.description")))
                                        .binding(10, () -> DCFixesConfig.get().reinforcedRotorShaftMass, value -> DCFixesConfig.get().reinforcedRotorShaftMass = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, Integer.MAX_VALUE))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_part_fluid_capacity"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_part_fluid_capacity.description")))
                                        .binding(500, () -> DCFixesConfig.get().reinforcedPartFluidCapacity, value -> DCFixesConfig.get().reinforcedPartFluidCapacity = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, Integer.MAX_VALUE))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("config.dcfixes.option.reinforced_max_fluid_capacity"))
                                        .description(OptionDescription.of(Component.translatable("config.dcfixes.option.reinforced_max_fluid_capacity.description")))
                                        .binding(300000, () -> DCFixesConfig.get().reinforcedMaxFluidCapacity, value -> DCFixesConfig.get().reinforcedMaxFluidCapacity = value)
                                        .controller(option -> IntegerFieldControllerBuilder.create(option).range(0, Integer.MAX_VALUE))
                                        .build())
                                .build())
                        .build())
                .save(DCFixesConfig::save)
                .build()
                .generateScreen(screen);
    }
}
