modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "super-early"
version = "1.0.0"
displayName = "Super Early"
logoFile = "../assets/super-early/icon.png"
description = '''Replaces the early loading screen of Forge'''
authors = "Bawnorton"